site_name: Fine-Tune Pipeline Documentation
site_description: A comprehensive fine-tuning pipeline for language models with evaluation and inference capabilities
site_author: Fine-Tune Pipeline Team
site_url: https://Fine-Tuning-Team.github.io/Fine-Tune-Pipeline

repo_name: Fine-Tune-Pipeline
repo_url: https://github.com/Fine-Tuning-Team/Fine-Tune-Pipeline
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate

  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Environment Setup: getting-started/environment-setup.md
  - Configuration:
    - Overview: configuration/overview.md
    - Fine-Tuner Config: configuration/fine-tuner.md
    - Inferencer Config: configuration/inferencer.md
    - Evaluator Config: configuration/evaluator.md
  - Components:
    - Pipeline Orchestrator: components/pipeline-orchestrator.md
    - Fine-Tuner: components/fine-tuner.md
    - Inferencer: components/inferencer.md
    - Evaluator: components/evaluator.md
  - Tutorials:
    - Basic Fine-Tuning: tutorials/basic-fine-tuning.md
    - Advanced Configuration: tutorials/advanced-configuration.md
    - CI/CD Integration: tutorials/ci-cd-integration.md
  - API Reference: api-reference.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Fine-Tuning-Team/Fine-Tune-Pipeline
