name: Deploy to RunPod

on:
  push:
    branches: [ main ]

jobs:
  deploy-runpod-instance:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Create RunPod Pod
      run: |
        response=$(curl --request POST \
          --url https://rest.runpod.io/v1/pods \
          --header 'Authorization: Bearer ${{ secrets.RUNPOD_API_KEY }}' \
          --header 'Content-Type: application/json' \
          --write-out "\nHTTP-STATUS:%{http_code}" \
          --data '{
          "cloudType": "SECURE",
          "computeType": "GPU",
          "containerDiskInGb": 50,
          "cpuFlavorPriority": "availability",
          "dataCenterIds": [
            "EU-RO-1", "CA-MTL-1", "EU-SE-1", "US-IL-1", "EUR-IS-1", "EU-CZ-1",
            "US-TX-3", "EUR-IS-2", "US-KS-2", "US-GA-2", "US-WA-1", "US-TX-1",
            "CA-MTL-3", "EU-NL-1", "US-TX-4", "US-CA-2", "US-NC-1", "OC-AU-1",
            "US-DE-1", "EUR-IS-3", "CA-MTL-2", "AP-JP-1", "EUR-NO-1", "EU-FR-1",
            "US-KS-3", "US-GA-1"
          ],
          "dataCenterPriority": "availability",
          "dockerEntrypoint": [],
          "dockerStartCmd": [],
          "env": {},
          "globalNetworking": false,
          "gpuCount": 1,
          "gpuTypePriority": "availability",
          "interruptible": false,
          "locked": false,
          "minRAMPerGPU": 8,
          "minVCPUPerGPU": 2,
          "name": "my-pod-from-github-actions",
          "ports": [
            "8888/http,22/tcp"
          ],
          "vcpuCount": 2,
          "volumeInGb": 20,
          "volumeMountPath": "/workspace"
        }')
        
        echo "API Response:"
        echo "$response"
